import { useState, useEffect } from 'react';
import '../policy-studio.css';

export const PolicyStudio = () => {
  const [nlPolicy, setNlPolicy] = useState("If the customer has a FICO score below 600, do not allow credit limit increases above $1,000 without human review.");
  const [simulating, setSimulating] = useState(false);

  useEffect(() => {
    // Mock re-compile effect
    setSimulating(true);
    const t = setTimeout(() => setSimulating(false), 800);
    return () => clearTimeout(t);
  }, [nlPolicy]);

  return (
    <div className="studio-layout">
      {/* Pane 1: Natural Language */}
      <div className="studio-pane pane-1">
        <div className="pane-header">
          <span className="pane-title">Intent (Natural Language)</span>
        </div>
        <div className="pane-content">
          <textarea 
            className={`nl-editor ${!simulating ? 'grammar-valid' : ''}`}
            value={nlPolicy}
            onChange={(e) => setNlPolicy(e.target.value)}
            spellCheck="false"
          />
        </div>
      </div>

      {/* Pane 2: OPA Rego Code */}
      <div className="studio-pane pane-2">
        <div className="pane-header">
          <span className="pane-title">Compiled Policy (Rego)</span>
        </div>
        <div className="pane-content rego-editor">
          {!simulating && (
            <div className="z3-badge">
              <div className="z3-dot"></div>
              <span className="z3-text">Z3 THEOREM PROVER: SOUND</span>
            </div>
          )}

          <div style={{ opacity: simulating ? 0.5 : 1, transition: 'opacity 300ms' }}>
            <span className="rego-comment"># Generated by AEGIS LLM Compiler</span><br /><br />
            <span className="rego-keyword">package</span> aegis.risk.credit<br /><br />
            <span className="rego-keyword">default</span> allow = <span className="rego-keyword">false</span><br /><br />
            allow {'{'} <br />
            &nbsp;&nbsp;input.action_type <span className="rego-operator">==</span> <span className="rego-string">"increase_limit"</span><br />
            &nbsp;&nbsp;input.customer.fico_score <span className="rego-operator">&lt;</span> 600<br />
            &nbsp;&nbsp;input.amount <span className="rego-operator">&gt;</span> 1000<br />
            &nbsp;&nbsp;input.context.human_reviewed <span className="rego-operator">==</span> <span className="rego-keyword">true</span><br />
            {'}'}<br /><br />
            
            <span className="rego-keyword">deny</span>[msg] {'{'} <br />
            &nbsp;&nbsp;input.action_type <span className="rego-operator">==</span> <span className="rego-string">"increase_limit"</span><br />
            &nbsp;&nbsp;input.customer.fico_score <span className="rego-operator">&lt;</span> 600<br />
            &nbsp;&nbsp;input.amount <span className="rego-operator">&gt;</span> 1000<br />
            &nbsp;&nbsp;<span className="rego-keyword">not</span> input.context.human_reviewed<br />
            &nbsp;&nbsp;msg <span className="rego-operator">:=</span> <span className="rego-string">"Credit increase over $1000 for sub-600 FICO requires human review."</span><br />
            {'}'}
          </div>
        </div>
      </div>

      {/* Pane 3: Simulation */}
      <div className="studio-pane pane-3">
        <div className="pane-header">
          <span className="pane-title">Backtest Simulation</span>
          <span style={{ fontSize: '10px', color: '#64748B', fontFamily: 'JetBrains Mono' }}>LAST 10,000 ACTIONS</span>
        </div>
        <div className="pane-content">
          <div className="sim-timeline" style={{ opacity: simulating ? 0.5 : 1, transition: 'opacity 300ms' }}>
            <div className="sim-item new-blocked">
              <div>
                <div className="sim-action">increase_limit ($2,500)</div>
                <div className="sim-meta">FICO: 580 · 09:14:32</div>
              </div>
              <div className="sim-status">NEWLY BLOCKED</div>
            </div>
            
            <div className="sim-item">
              <div>
                <div className="sim-action">increase_limit ($500)</div>
                <div className="sim-meta">FICO: 550 · 09:12:11</div>
              </div>
              <div className="sim-status" style={{ color: '#64748B' }}>NO CHANGE (ALLOWED)</div>
            </div>
            
            <div className="sim-item new-blocked">
              <div>
                <div className="sim-action">increase_limit ($1,200)</div>
                <div className="sim-meta">FICO: 595 · 08:45:02</div>
              </div>
              <div className="sim-status">NEWLY BLOCKED</div>
            </div>

            <div className="sim-item">
              <div>
                <div className="sim-action">increase_limit ($5,000)</div>
                <div className="sim-meta">FICO: 720 · 08:10:00</div>
              </div>
              <div className="sim-status" style={{ color: '#64748B' }}>NO CHANGE (ALLOWED)</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
